# Generated by Django 3.2.7 on 2021-09-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='', max_length=70)),
                ('email', models.EmailField(default='', max_length=200)),
                ('passwd', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
